### PR TITLE
converted to webpack 2 from webpack 1

### PR DESCRIPTION
**Pull request by Rafi993**
Converted webpack 1 to webpack 2 and made few changes in build too. It could also use installer creation in build process. Possibly using https://www.electron.build/

### CODE REVIEW

**Comment by Rafi993** [comment]
Since this repo seems to be inactive I'm closing this pull request and keep it as a separate repo.

**Comment by bortexz** [comment]
Hi @Rafi993 , you're right this repo is inactive as of today, but if you want to continue the work I can make you collaborator of the project so you can push to it directly :)

**Comment by bortexz** [comment]
I merge the PR, because there is no testing yet, I trust you have tried it and works. 

Thanks for the PR and getting interested in the project!

**Comment by Rafi993** [comment]
The name change I did to camelid in readme.MD needs to be reverted

**Pull request merged**
